title: "Sagni Majumdar"
description: "Personal website showcasing my professional background, co-curricular activities, LinkedIn, and updates."
theme: jekyll-theme-hacker
url: "https://thesagni.github.io"
